// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var ATBarHistoryType, ATConstituentRequestTypes, ATStreamRequestTypes;

  ATConstituentRequestTypes = ['ATConstituentListIndex', 'ATConstituentListSector', 'ATConstituentListOptionChain'];

  ATStreamRequestTypes = ['StreamRequestSubscribe', 'StreamRequestUnsubscribe', 'StreamRequestSubscribeQuotesOnly', 'StreamRequestUnsubscribeQuotesOnly', 'StreamRequestSubscribeTradesOnly', 'StreamRequestUnsubscribeTradesOnly'];

  ATBarHistoryType = ['BarHistoryIntraday', 'BarHistoryDaily', 'BarHistoryWeekly'];

  module.exports = {
    ATConstituentRequestTypes: ATConstituentRequestTypes,
    ATStreamRequestTypes: ATStreamRequestTypes,
    ATBarHistoryType: ATBarHistoryType
  };

}).call(this);
