// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef PROTOBUF_messages_2eproto__INCLUDED
#define PROTOBUF_messages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace NodeActiveTickProto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messages_2eproto();
void protobuf_AssignDesc_messages_2eproto();
void protobuf_ShutdownFile_messages_2eproto();

class ATLoginResponse;
class ATConstituentResponse;
class ATQuoteStreamResponse;
class ATServerTime;
class ATSymbol;
class ATPrice;
class ATQuote;

// ===================================================================

class ATLoginResponse : public ::google::protobuf::Message {
 public:
  ATLoginResponse();
  virtual ~ATLoginResponse();

  ATLoginResponse(const ATLoginResponse& from);

  inline ATLoginResponse& operator=(const ATLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ATLoginResponse& default_instance();

  void Swap(ATLoginResponse* other);

  // implements Message ----------------------------------------------

  ATLoginResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ATLoginResponse& from);
  void MergeFrom(const ATLoginResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 loginResponseType = 1;
  inline bool has_loginresponsetype() const;
  inline void clear_loginresponsetype();
  static const int kLoginResponseTypeFieldNumber = 1;
  inline ::google::protobuf::int32 loginresponsetype() const;
  inline void set_loginresponsetype(::google::protobuf::int32 value);

  // required string loginResponseString = 2;
  inline bool has_loginresponsestring() const;
  inline void clear_loginresponsestring();
  static const int kLoginResponseStringFieldNumber = 2;
  inline const ::std::string& loginresponsestring() const;
  inline void set_loginresponsestring(const ::std::string& value);
  inline void set_loginresponsestring(const char* value);
  inline void set_loginresponsestring(const char* value, size_t size);
  inline ::std::string* mutable_loginresponsestring();
  inline ::std::string* release_loginresponsestring();
  inline void set_allocated_loginresponsestring(::std::string* loginresponsestring);

  // @@protoc_insertion_point(class_scope:NodeActiveTickProto.ATLoginResponse)
 private:
  inline void set_has_loginresponsetype();
  inline void clear_has_loginresponsetype();
  inline void set_has_loginresponsestring();
  inline void clear_has_loginresponsestring();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* loginresponsestring_;
  ::google::protobuf::int32 loginresponsetype_;
  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static ATLoginResponse* default_instance_;
};
// -------------------------------------------------------------------

class ATConstituentResponse : public ::google::protobuf::Message {
 public:
  ATConstituentResponse();
  virtual ~ATConstituentResponse();

  ATConstituentResponse(const ATConstituentResponse& from);

  inline ATConstituentResponse& operator=(const ATConstituentResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ATConstituentResponse& default_instance();

  void Swap(ATConstituentResponse* other);

  // implements Message ----------------------------------------------

  ATConstituentResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ATConstituentResponse& from);
  void MergeFrom(const ATConstituentResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .NodeActiveTickProto.ATSymbol symbols = 1;
  inline int symbols_size() const;
  inline void clear_symbols();
  static const int kSymbolsFieldNumber = 1;
  inline const ::NodeActiveTickProto::ATSymbol& symbols(int index) const;
  inline ::NodeActiveTickProto::ATSymbol* mutable_symbols(int index);
  inline ::NodeActiveTickProto::ATSymbol* add_symbols();
  inline const ::google::protobuf::RepeatedPtrField< ::NodeActiveTickProto::ATSymbol >&
      symbols() const;
  inline ::google::protobuf::RepeatedPtrField< ::NodeActiveTickProto::ATSymbol >*
      mutable_symbols();

  // @@protoc_insertion_point(class_scope:NodeActiveTickProto.ATConstituentResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::NodeActiveTickProto::ATSymbol > symbols_;
  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static ATConstituentResponse* default_instance_;
};
// -------------------------------------------------------------------

class ATQuoteStreamResponse : public ::google::protobuf::Message {
 public:
  ATQuoteStreamResponse();
  virtual ~ATQuoteStreamResponse();

  ATQuoteStreamResponse(const ATQuoteStreamResponse& from);

  inline ATQuoteStreamResponse& operator=(const ATQuoteStreamResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ATQuoteStreamResponse& default_instance();

  void Swap(ATQuoteStreamResponse* other);

  // implements Message ----------------------------------------------

  ATQuoteStreamResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ATQuoteStreamResponse& from);
  void MergeFrom(const ATQuoteStreamResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string quoteStreamResponseType = 1;
  inline bool has_quotestreamresponsetype() const;
  inline void clear_quotestreamresponsetype();
  static const int kQuoteStreamResponseTypeFieldNumber = 1;
  inline const ::std::string& quotestreamresponsetype() const;
  inline void set_quotestreamresponsetype(const ::std::string& value);
  inline void set_quotestreamresponsetype(const char* value);
  inline void set_quotestreamresponsetype(const char* value, size_t size);
  inline ::std::string* mutable_quotestreamresponsetype();
  inline ::std::string* release_quotestreamresponsetype();
  inline void set_allocated_quotestreamresponsetype(::std::string* quotestreamresponsetype);

  // optional int32 quoteResponseCount = 2;
  inline bool has_quoteresponsecount() const;
  inline void clear_quoteresponsecount();
  static const int kQuoteResponseCountFieldNumber = 2;
  inline ::google::protobuf::int32 quoteresponsecount() const;
  inline void set_quoteresponsecount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NodeActiveTickProto.ATQuoteStreamResponse)
 private:
  inline void set_has_quotestreamresponsetype();
  inline void clear_has_quotestreamresponsetype();
  inline void set_has_quoteresponsecount();
  inline void clear_has_quoteresponsecount();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* quotestreamresponsetype_;
  ::google::protobuf::int32 quoteresponsecount_;
  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static ATQuoteStreamResponse* default_instance_;
};
// -------------------------------------------------------------------

class ATServerTime : public ::google::protobuf::Message {
 public:
  ATServerTime();
  virtual ~ATServerTime();

  ATServerTime(const ATServerTime& from);

  inline ATServerTime& operator=(const ATServerTime& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ATServerTime& default_instance();

  void Swap(ATServerTime* other);

  // implements Message ----------------------------------------------

  ATServerTime* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ATServerTime& from);
  void MergeFrom(const ATServerTime& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 year = 1;
  inline bool has_year() const;
  inline void clear_year();
  static const int kYearFieldNumber = 1;
  inline ::google::protobuf::int32 year() const;
  inline void set_year(::google::protobuf::int32 value);

  // required int32 month = 2;
  inline bool has_month() const;
  inline void clear_month();
  static const int kMonthFieldNumber = 2;
  inline ::google::protobuf::int32 month() const;
  inline void set_month(::google::protobuf::int32 value);

  // required int32 dayOfWeek = 3;
  inline bool has_dayofweek() const;
  inline void clear_dayofweek();
  static const int kDayOfWeekFieldNumber = 3;
  inline ::google::protobuf::int32 dayofweek() const;
  inline void set_dayofweek(::google::protobuf::int32 value);

  // required int32 day = 4;
  inline bool has_day() const;
  inline void clear_day();
  static const int kDayFieldNumber = 4;
  inline ::google::protobuf::int32 day() const;
  inline void set_day(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NodeActiveTickProto.ATServerTime)
 private:
  inline void set_has_year();
  inline void clear_has_year();
  inline void set_has_month();
  inline void clear_has_month();
  inline void set_has_dayofweek();
  inline void clear_has_dayofweek();
  inline void set_has_day();
  inline void clear_has_day();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 year_;
  ::google::protobuf::int32 month_;
  ::google::protobuf::int32 dayofweek_;
  ::google::protobuf::int32 day_;
  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static ATServerTime* default_instance_;
};
// -------------------------------------------------------------------

class ATSymbol : public ::google::protobuf::Message {
 public:
  ATSymbol();
  virtual ~ATSymbol();

  ATSymbol(const ATSymbol& from);

  inline ATSymbol& operator=(const ATSymbol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ATSymbol& default_instance();

  void Swap(ATSymbol* other);

  // implements Message ----------------------------------------------

  ATSymbol* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ATSymbol& from);
  void MergeFrom(const ATSymbol& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string symbol = 1;
  inline bool has_symbol() const;
  inline void clear_symbol();
  static const int kSymbolFieldNumber = 1;
  inline const ::std::string& symbol() const;
  inline void set_symbol(const ::std::string& value);
  inline void set_symbol(const char* value);
  inline void set_symbol(const char* value, size_t size);
  inline ::std::string* mutable_symbol();
  inline ::std::string* release_symbol();
  inline void set_allocated_symbol(::std::string* symbol);

  // optional int32 symbolType = 2;
  inline bool has_symboltype() const;
  inline void clear_symboltype();
  static const int kSymbolTypeFieldNumber = 2;
  inline ::google::protobuf::int32 symboltype() const;
  inline void set_symboltype(::google::protobuf::int32 value);

  // optional int32 exchangeType = 3;
  inline bool has_exchangetype() const;
  inline void clear_exchangetype();
  static const int kExchangeTypeFieldNumber = 3;
  inline ::google::protobuf::int32 exchangetype() const;
  inline void set_exchangetype(::google::protobuf::int32 value);

  // optional int32 countryType = 4;
  inline bool has_countrytype() const;
  inline void clear_countrytype();
  static const int kCountryTypeFieldNumber = 4;
  inline ::google::protobuf::int32 countrytype() const;
  inline void set_countrytype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NodeActiveTickProto.ATSymbol)
 private:
  inline void set_has_symbol();
  inline void clear_has_symbol();
  inline void set_has_symboltype();
  inline void clear_has_symboltype();
  inline void set_has_exchangetype();
  inline void clear_has_exchangetype();
  inline void set_has_countrytype();
  inline void clear_has_countrytype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* symbol_;
  ::google::protobuf::int32 symboltype_;
  ::google::protobuf::int32 exchangetype_;
  ::google::protobuf::int32 countrytype_;
  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static ATSymbol* default_instance_;
};
// -------------------------------------------------------------------

class ATPrice : public ::google::protobuf::Message {
 public:
  ATPrice();
  virtual ~ATPrice();

  ATPrice(const ATPrice& from);

  inline ATPrice& operator=(const ATPrice& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ATPrice& default_instance();

  void Swap(ATPrice* other);

  // implements Message ----------------------------------------------

  ATPrice* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ATPrice& from);
  void MergeFrom(const ATPrice& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double price = 1;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 1;
  inline double price() const;
  inline void set_price(double value);

  // required int32 precision = 2;
  inline bool has_precision() const;
  inline void clear_precision();
  static const int kPrecisionFieldNumber = 2;
  inline ::google::protobuf::int32 precision() const;
  inline void set_precision(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NodeActiveTickProto.ATPrice)
 private:
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_precision();
  inline void clear_has_precision();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double price_;
  ::google::protobuf::int32 precision_;
  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static ATPrice* default_instance_;
};
// -------------------------------------------------------------------

class ATQuote : public ::google::protobuf::Message {
 public:
  ATQuote();
  virtual ~ATQuote();

  ATQuote(const ATQuote& from);

  inline ATQuote& operator=(const ATQuote& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ATQuote& default_instance();

  void Swap(ATQuote* other);

  // implements Message ----------------------------------------------

  ATQuote* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ATQuote& from);
  void MergeFrom(const ATQuote& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .NodeActiveTickProto.ATSymbol symbol = 1;
  inline bool has_symbol() const;
  inline void clear_symbol();
  static const int kSymbolFieldNumber = 1;
  inline const ::NodeActiveTickProto::ATSymbol& symbol() const;
  inline ::NodeActiveTickProto::ATSymbol* mutable_symbol();
  inline ::NodeActiveTickProto::ATSymbol* release_symbol();
  inline void set_allocated_symbol(::NodeActiveTickProto::ATSymbol* symbol);

  // required .NodeActiveTickProto.ATPrice bidPrice = 2;
  inline bool has_bidprice() const;
  inline void clear_bidprice();
  static const int kBidPriceFieldNumber = 2;
  inline const ::NodeActiveTickProto::ATPrice& bidprice() const;
  inline ::NodeActiveTickProto::ATPrice* mutable_bidprice();
  inline ::NodeActiveTickProto::ATPrice* release_bidprice();
  inline void set_allocated_bidprice(::NodeActiveTickProto::ATPrice* bidprice);

  // required .NodeActiveTickProto.ATPrice askPrice = 3;
  inline bool has_askprice() const;
  inline void clear_askprice();
  static const int kAskPriceFieldNumber = 3;
  inline const ::NodeActiveTickProto::ATPrice& askprice() const;
  inline ::NodeActiveTickProto::ATPrice* mutable_askprice();
  inline ::NodeActiveTickProto::ATPrice* release_askprice();
  inline void set_allocated_askprice(::NodeActiveTickProto::ATPrice* askprice);

  // optional int32 bidSize = 4;
  inline bool has_bidsize() const;
  inline void clear_bidsize();
  static const int kBidSizeFieldNumber = 4;
  inline ::google::protobuf::int32 bidsize() const;
  inline void set_bidsize(::google::protobuf::int32 value);

  // optional int32 askSize = 5;
  inline bool has_asksize() const;
  inline void clear_asksize();
  static const int kAskSizeFieldNumber = 5;
  inline ::google::protobuf::int32 asksize() const;
  inline void set_asksize(::google::protobuf::int32 value);

  // optional int32 quoteConditionId = 6;
  inline bool has_quoteconditionid() const;
  inline void clear_quoteconditionid();
  static const int kQuoteConditionIdFieldNumber = 6;
  inline ::google::protobuf::int32 quoteconditionid() const;
  inline void set_quoteconditionid(::google::protobuf::int32 value);

  // optional .NodeActiveTickProto.ATServerTime serverTime = 7;
  inline bool has_servertime() const;
  inline void clear_servertime();
  static const int kServerTimeFieldNumber = 7;
  inline const ::NodeActiveTickProto::ATServerTime& servertime() const;
  inline ::NodeActiveTickProto::ATServerTime* mutable_servertime();
  inline ::NodeActiveTickProto::ATServerTime* release_servertime();
  inline void set_allocated_servertime(::NodeActiveTickProto::ATServerTime* servertime);

  // optional int32 bidExchangeId = 8;
  inline bool has_bidexchangeid() const;
  inline void clear_bidexchangeid();
  static const int kBidExchangeIdFieldNumber = 8;
  inline ::google::protobuf::int32 bidexchangeid() const;
  inline void set_bidexchangeid(::google::protobuf::int32 value);

  // optional int32 askExchangeId = 9;
  inline bool has_askexchangeid() const;
  inline void clear_askexchangeid();
  static const int kAskExchangeIdFieldNumber = 9;
  inline ::google::protobuf::int32 askexchangeid() const;
  inline void set_askexchangeid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NodeActiveTickProto.ATQuote)
 private:
  inline void set_has_symbol();
  inline void clear_has_symbol();
  inline void set_has_bidprice();
  inline void clear_has_bidprice();
  inline void set_has_askprice();
  inline void clear_has_askprice();
  inline void set_has_bidsize();
  inline void clear_has_bidsize();
  inline void set_has_asksize();
  inline void clear_has_asksize();
  inline void set_has_quoteconditionid();
  inline void clear_has_quoteconditionid();
  inline void set_has_servertime();
  inline void clear_has_servertime();
  inline void set_has_bidexchangeid();
  inline void clear_has_bidexchangeid();
  inline void set_has_askexchangeid();
  inline void clear_has_askexchangeid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::NodeActiveTickProto::ATSymbol* symbol_;
  ::NodeActiveTickProto::ATPrice* bidprice_;
  ::NodeActiveTickProto::ATPrice* askprice_;
  ::google::protobuf::int32 bidsize_;
  ::google::protobuf::int32 asksize_;
  ::NodeActiveTickProto::ATServerTime* servertime_;
  ::google::protobuf::int32 quoteconditionid_;
  ::google::protobuf::int32 bidexchangeid_;
  ::google::protobuf::int32 askexchangeid_;
  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static ATQuote* default_instance_;
};
// ===================================================================


// ===================================================================

// ATLoginResponse

// required int32 loginResponseType = 1;
inline bool ATLoginResponse::has_loginresponsetype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ATLoginResponse::set_has_loginresponsetype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ATLoginResponse::clear_has_loginresponsetype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ATLoginResponse::clear_loginresponsetype() {
  loginresponsetype_ = 0;
  clear_has_loginresponsetype();
}
inline ::google::protobuf::int32 ATLoginResponse::loginresponsetype() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATLoginResponse.loginResponseType)
  return loginresponsetype_;
}
inline void ATLoginResponse::set_loginresponsetype(::google::protobuf::int32 value) {
  set_has_loginresponsetype();
  loginresponsetype_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATLoginResponse.loginResponseType)
}

// required string loginResponseString = 2;
inline bool ATLoginResponse::has_loginresponsestring() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ATLoginResponse::set_has_loginresponsestring() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ATLoginResponse::clear_has_loginresponsestring() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ATLoginResponse::clear_loginresponsestring() {
  if (loginresponsestring_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginresponsestring_->clear();
  }
  clear_has_loginresponsestring();
}
inline const ::std::string& ATLoginResponse::loginresponsestring() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATLoginResponse.loginResponseString)
  return *loginresponsestring_;
}
inline void ATLoginResponse::set_loginresponsestring(const ::std::string& value) {
  set_has_loginresponsestring();
  if (loginresponsestring_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginresponsestring_ = new ::std::string;
  }
  loginresponsestring_->assign(value);
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATLoginResponse.loginResponseString)
}
inline void ATLoginResponse::set_loginresponsestring(const char* value) {
  set_has_loginresponsestring();
  if (loginresponsestring_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginresponsestring_ = new ::std::string;
  }
  loginresponsestring_->assign(value);
  // @@protoc_insertion_point(field_set_char:NodeActiveTickProto.ATLoginResponse.loginResponseString)
}
inline void ATLoginResponse::set_loginresponsestring(const char* value, size_t size) {
  set_has_loginresponsestring();
  if (loginresponsestring_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginresponsestring_ = new ::std::string;
  }
  loginresponsestring_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NodeActiveTickProto.ATLoginResponse.loginResponseString)
}
inline ::std::string* ATLoginResponse::mutable_loginresponsestring() {
  set_has_loginresponsestring();
  if (loginresponsestring_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginresponsestring_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:NodeActiveTickProto.ATLoginResponse.loginResponseString)
  return loginresponsestring_;
}
inline ::std::string* ATLoginResponse::release_loginresponsestring() {
  clear_has_loginresponsestring();
  if (loginresponsestring_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = loginresponsestring_;
    loginresponsestring_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ATLoginResponse::set_allocated_loginresponsestring(::std::string* loginresponsestring) {
  if (loginresponsestring_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete loginresponsestring_;
  }
  if (loginresponsestring) {
    set_has_loginresponsestring();
    loginresponsestring_ = loginresponsestring;
  } else {
    clear_has_loginresponsestring();
    loginresponsestring_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:NodeActiveTickProto.ATLoginResponse.loginResponseString)
}

// -------------------------------------------------------------------

// ATConstituentResponse

// repeated .NodeActiveTickProto.ATSymbol symbols = 1;
inline int ATConstituentResponse::symbols_size() const {
  return symbols_.size();
}
inline void ATConstituentResponse::clear_symbols() {
  symbols_.Clear();
}
inline const ::NodeActiveTickProto::ATSymbol& ATConstituentResponse::symbols(int index) const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATConstituentResponse.symbols)
  return symbols_.Get(index);
}
inline ::NodeActiveTickProto::ATSymbol* ATConstituentResponse::mutable_symbols(int index) {
  // @@protoc_insertion_point(field_mutable:NodeActiveTickProto.ATConstituentResponse.symbols)
  return symbols_.Mutable(index);
}
inline ::NodeActiveTickProto::ATSymbol* ATConstituentResponse::add_symbols() {
  // @@protoc_insertion_point(field_add:NodeActiveTickProto.ATConstituentResponse.symbols)
  return symbols_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::NodeActiveTickProto::ATSymbol >&
ATConstituentResponse::symbols() const {
  // @@protoc_insertion_point(field_list:NodeActiveTickProto.ATConstituentResponse.symbols)
  return symbols_;
}
inline ::google::protobuf::RepeatedPtrField< ::NodeActiveTickProto::ATSymbol >*
ATConstituentResponse::mutable_symbols() {
  // @@protoc_insertion_point(field_mutable_list:NodeActiveTickProto.ATConstituentResponse.symbols)
  return &symbols_;
}

// -------------------------------------------------------------------

// ATQuoteStreamResponse

// optional string quoteStreamResponseType = 1;
inline bool ATQuoteStreamResponse::has_quotestreamresponsetype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ATQuoteStreamResponse::set_has_quotestreamresponsetype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ATQuoteStreamResponse::clear_has_quotestreamresponsetype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ATQuoteStreamResponse::clear_quotestreamresponsetype() {
  if (quotestreamresponsetype_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quotestreamresponsetype_->clear();
  }
  clear_has_quotestreamresponsetype();
}
inline const ::std::string& ATQuoteStreamResponse::quotestreamresponsetype() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuoteStreamResponse.quoteStreamResponseType)
  return *quotestreamresponsetype_;
}
inline void ATQuoteStreamResponse::set_quotestreamresponsetype(const ::std::string& value) {
  set_has_quotestreamresponsetype();
  if (quotestreamresponsetype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quotestreamresponsetype_ = new ::std::string;
  }
  quotestreamresponsetype_->assign(value);
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATQuoteStreamResponse.quoteStreamResponseType)
}
inline void ATQuoteStreamResponse::set_quotestreamresponsetype(const char* value) {
  set_has_quotestreamresponsetype();
  if (quotestreamresponsetype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quotestreamresponsetype_ = new ::std::string;
  }
  quotestreamresponsetype_->assign(value);
  // @@protoc_insertion_point(field_set_char:NodeActiveTickProto.ATQuoteStreamResponse.quoteStreamResponseType)
}
inline void ATQuoteStreamResponse::set_quotestreamresponsetype(const char* value, size_t size) {
  set_has_quotestreamresponsetype();
  if (quotestreamresponsetype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quotestreamresponsetype_ = new ::std::string;
  }
  quotestreamresponsetype_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NodeActiveTickProto.ATQuoteStreamResponse.quoteStreamResponseType)
}
inline ::std::string* ATQuoteStreamResponse::mutable_quotestreamresponsetype() {
  set_has_quotestreamresponsetype();
  if (quotestreamresponsetype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    quotestreamresponsetype_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:NodeActiveTickProto.ATQuoteStreamResponse.quoteStreamResponseType)
  return quotestreamresponsetype_;
}
inline ::std::string* ATQuoteStreamResponse::release_quotestreamresponsetype() {
  clear_has_quotestreamresponsetype();
  if (quotestreamresponsetype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = quotestreamresponsetype_;
    quotestreamresponsetype_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ATQuoteStreamResponse::set_allocated_quotestreamresponsetype(::std::string* quotestreamresponsetype) {
  if (quotestreamresponsetype_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete quotestreamresponsetype_;
  }
  if (quotestreamresponsetype) {
    set_has_quotestreamresponsetype();
    quotestreamresponsetype_ = quotestreamresponsetype;
  } else {
    clear_has_quotestreamresponsetype();
    quotestreamresponsetype_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:NodeActiveTickProto.ATQuoteStreamResponse.quoteStreamResponseType)
}

// optional int32 quoteResponseCount = 2;
inline bool ATQuoteStreamResponse::has_quoteresponsecount() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ATQuoteStreamResponse::set_has_quoteresponsecount() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ATQuoteStreamResponse::clear_has_quoteresponsecount() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ATQuoteStreamResponse::clear_quoteresponsecount() {
  quoteresponsecount_ = 0;
  clear_has_quoteresponsecount();
}
inline ::google::protobuf::int32 ATQuoteStreamResponse::quoteresponsecount() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuoteStreamResponse.quoteResponseCount)
  return quoteresponsecount_;
}
inline void ATQuoteStreamResponse::set_quoteresponsecount(::google::protobuf::int32 value) {
  set_has_quoteresponsecount();
  quoteresponsecount_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATQuoteStreamResponse.quoteResponseCount)
}

// -------------------------------------------------------------------

// ATServerTime

// required int32 year = 1;
inline bool ATServerTime::has_year() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ATServerTime::set_has_year() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ATServerTime::clear_has_year() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ATServerTime::clear_year() {
  year_ = 0;
  clear_has_year();
}
inline ::google::protobuf::int32 ATServerTime::year() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATServerTime.year)
  return year_;
}
inline void ATServerTime::set_year(::google::protobuf::int32 value) {
  set_has_year();
  year_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATServerTime.year)
}

// required int32 month = 2;
inline bool ATServerTime::has_month() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ATServerTime::set_has_month() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ATServerTime::clear_has_month() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ATServerTime::clear_month() {
  month_ = 0;
  clear_has_month();
}
inline ::google::protobuf::int32 ATServerTime::month() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATServerTime.month)
  return month_;
}
inline void ATServerTime::set_month(::google::protobuf::int32 value) {
  set_has_month();
  month_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATServerTime.month)
}

// required int32 dayOfWeek = 3;
inline bool ATServerTime::has_dayofweek() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ATServerTime::set_has_dayofweek() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ATServerTime::clear_has_dayofweek() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ATServerTime::clear_dayofweek() {
  dayofweek_ = 0;
  clear_has_dayofweek();
}
inline ::google::protobuf::int32 ATServerTime::dayofweek() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATServerTime.dayOfWeek)
  return dayofweek_;
}
inline void ATServerTime::set_dayofweek(::google::protobuf::int32 value) {
  set_has_dayofweek();
  dayofweek_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATServerTime.dayOfWeek)
}

// required int32 day = 4;
inline bool ATServerTime::has_day() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ATServerTime::set_has_day() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ATServerTime::clear_has_day() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ATServerTime::clear_day() {
  day_ = 0;
  clear_has_day();
}
inline ::google::protobuf::int32 ATServerTime::day() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATServerTime.day)
  return day_;
}
inline void ATServerTime::set_day(::google::protobuf::int32 value) {
  set_has_day();
  day_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATServerTime.day)
}

// -------------------------------------------------------------------

// ATSymbol

// required string symbol = 1;
inline bool ATSymbol::has_symbol() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ATSymbol::set_has_symbol() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ATSymbol::clear_has_symbol() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ATSymbol::clear_symbol() {
  if (symbol_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    symbol_->clear();
  }
  clear_has_symbol();
}
inline const ::std::string& ATSymbol::symbol() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATSymbol.symbol)
  return *symbol_;
}
inline void ATSymbol::set_symbol(const ::std::string& value) {
  set_has_symbol();
  if (symbol_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(value);
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATSymbol.symbol)
}
inline void ATSymbol::set_symbol(const char* value) {
  set_has_symbol();
  if (symbol_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(value);
  // @@protoc_insertion_point(field_set_char:NodeActiveTickProto.ATSymbol.symbol)
}
inline void ATSymbol::set_symbol(const char* value, size_t size) {
  set_has_symbol();
  if (symbol_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NodeActiveTickProto.ATSymbol.symbol)
}
inline ::std::string* ATSymbol::mutable_symbol() {
  set_has_symbol();
  if (symbol_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    symbol_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:NodeActiveTickProto.ATSymbol.symbol)
  return symbol_;
}
inline ::std::string* ATSymbol::release_symbol() {
  clear_has_symbol();
  if (symbol_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = symbol_;
    symbol_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ATSymbol::set_allocated_symbol(::std::string* symbol) {
  if (symbol_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete symbol_;
  }
  if (symbol) {
    set_has_symbol();
    symbol_ = symbol;
  } else {
    clear_has_symbol();
    symbol_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:NodeActiveTickProto.ATSymbol.symbol)
}

// optional int32 symbolType = 2;
inline bool ATSymbol::has_symboltype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ATSymbol::set_has_symboltype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ATSymbol::clear_has_symboltype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ATSymbol::clear_symboltype() {
  symboltype_ = 0;
  clear_has_symboltype();
}
inline ::google::protobuf::int32 ATSymbol::symboltype() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATSymbol.symbolType)
  return symboltype_;
}
inline void ATSymbol::set_symboltype(::google::protobuf::int32 value) {
  set_has_symboltype();
  symboltype_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATSymbol.symbolType)
}

// optional int32 exchangeType = 3;
inline bool ATSymbol::has_exchangetype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ATSymbol::set_has_exchangetype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ATSymbol::clear_has_exchangetype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ATSymbol::clear_exchangetype() {
  exchangetype_ = 0;
  clear_has_exchangetype();
}
inline ::google::protobuf::int32 ATSymbol::exchangetype() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATSymbol.exchangeType)
  return exchangetype_;
}
inline void ATSymbol::set_exchangetype(::google::protobuf::int32 value) {
  set_has_exchangetype();
  exchangetype_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATSymbol.exchangeType)
}

// optional int32 countryType = 4;
inline bool ATSymbol::has_countrytype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ATSymbol::set_has_countrytype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ATSymbol::clear_has_countrytype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ATSymbol::clear_countrytype() {
  countrytype_ = 0;
  clear_has_countrytype();
}
inline ::google::protobuf::int32 ATSymbol::countrytype() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATSymbol.countryType)
  return countrytype_;
}
inline void ATSymbol::set_countrytype(::google::protobuf::int32 value) {
  set_has_countrytype();
  countrytype_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATSymbol.countryType)
}

// -------------------------------------------------------------------

// ATPrice

// required double price = 1;
inline bool ATPrice::has_price() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ATPrice::set_has_price() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ATPrice::clear_has_price() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ATPrice::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline double ATPrice::price() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATPrice.price)
  return price_;
}
inline void ATPrice::set_price(double value) {
  set_has_price();
  price_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATPrice.price)
}

// required int32 precision = 2;
inline bool ATPrice::has_precision() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ATPrice::set_has_precision() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ATPrice::clear_has_precision() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ATPrice::clear_precision() {
  precision_ = 0;
  clear_has_precision();
}
inline ::google::protobuf::int32 ATPrice::precision() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATPrice.precision)
  return precision_;
}
inline void ATPrice::set_precision(::google::protobuf::int32 value) {
  set_has_precision();
  precision_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATPrice.precision)
}

// -------------------------------------------------------------------

// ATQuote

// required .NodeActiveTickProto.ATSymbol symbol = 1;
inline bool ATQuote::has_symbol() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ATQuote::set_has_symbol() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ATQuote::clear_has_symbol() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ATQuote::clear_symbol() {
  if (symbol_ != NULL) symbol_->::NodeActiveTickProto::ATSymbol::Clear();
  clear_has_symbol();
}
inline const ::NodeActiveTickProto::ATSymbol& ATQuote::symbol() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.symbol)
  return symbol_ != NULL ? *symbol_ : *default_instance_->symbol_;
}
inline ::NodeActiveTickProto::ATSymbol* ATQuote::mutable_symbol() {
  set_has_symbol();
  if (symbol_ == NULL) symbol_ = new ::NodeActiveTickProto::ATSymbol;
  // @@protoc_insertion_point(field_mutable:NodeActiveTickProto.ATQuote.symbol)
  return symbol_;
}
inline ::NodeActiveTickProto::ATSymbol* ATQuote::release_symbol() {
  clear_has_symbol();
  ::NodeActiveTickProto::ATSymbol* temp = symbol_;
  symbol_ = NULL;
  return temp;
}
inline void ATQuote::set_allocated_symbol(::NodeActiveTickProto::ATSymbol* symbol) {
  delete symbol_;
  symbol_ = symbol;
  if (symbol) {
    set_has_symbol();
  } else {
    clear_has_symbol();
  }
  // @@protoc_insertion_point(field_set_allocated:NodeActiveTickProto.ATQuote.symbol)
}

// required .NodeActiveTickProto.ATPrice bidPrice = 2;
inline bool ATQuote::has_bidprice() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ATQuote::set_has_bidprice() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ATQuote::clear_has_bidprice() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ATQuote::clear_bidprice() {
  if (bidprice_ != NULL) bidprice_->::NodeActiveTickProto::ATPrice::Clear();
  clear_has_bidprice();
}
inline const ::NodeActiveTickProto::ATPrice& ATQuote::bidprice() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.bidPrice)
  return bidprice_ != NULL ? *bidprice_ : *default_instance_->bidprice_;
}
inline ::NodeActiveTickProto::ATPrice* ATQuote::mutable_bidprice() {
  set_has_bidprice();
  if (bidprice_ == NULL) bidprice_ = new ::NodeActiveTickProto::ATPrice;
  // @@protoc_insertion_point(field_mutable:NodeActiveTickProto.ATQuote.bidPrice)
  return bidprice_;
}
inline ::NodeActiveTickProto::ATPrice* ATQuote::release_bidprice() {
  clear_has_bidprice();
  ::NodeActiveTickProto::ATPrice* temp = bidprice_;
  bidprice_ = NULL;
  return temp;
}
inline void ATQuote::set_allocated_bidprice(::NodeActiveTickProto::ATPrice* bidprice) {
  delete bidprice_;
  bidprice_ = bidprice;
  if (bidprice) {
    set_has_bidprice();
  } else {
    clear_has_bidprice();
  }
  // @@protoc_insertion_point(field_set_allocated:NodeActiveTickProto.ATQuote.bidPrice)
}

// required .NodeActiveTickProto.ATPrice askPrice = 3;
inline bool ATQuote::has_askprice() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ATQuote::set_has_askprice() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ATQuote::clear_has_askprice() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ATQuote::clear_askprice() {
  if (askprice_ != NULL) askprice_->::NodeActiveTickProto::ATPrice::Clear();
  clear_has_askprice();
}
inline const ::NodeActiveTickProto::ATPrice& ATQuote::askprice() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.askPrice)
  return askprice_ != NULL ? *askprice_ : *default_instance_->askprice_;
}
inline ::NodeActiveTickProto::ATPrice* ATQuote::mutable_askprice() {
  set_has_askprice();
  if (askprice_ == NULL) askprice_ = new ::NodeActiveTickProto::ATPrice;
  // @@protoc_insertion_point(field_mutable:NodeActiveTickProto.ATQuote.askPrice)
  return askprice_;
}
inline ::NodeActiveTickProto::ATPrice* ATQuote::release_askprice() {
  clear_has_askprice();
  ::NodeActiveTickProto::ATPrice* temp = askprice_;
  askprice_ = NULL;
  return temp;
}
inline void ATQuote::set_allocated_askprice(::NodeActiveTickProto::ATPrice* askprice) {
  delete askprice_;
  askprice_ = askprice;
  if (askprice) {
    set_has_askprice();
  } else {
    clear_has_askprice();
  }
  // @@protoc_insertion_point(field_set_allocated:NodeActiveTickProto.ATQuote.askPrice)
}

// optional int32 bidSize = 4;
inline bool ATQuote::has_bidsize() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ATQuote::set_has_bidsize() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ATQuote::clear_has_bidsize() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ATQuote::clear_bidsize() {
  bidsize_ = 0;
  clear_has_bidsize();
}
inline ::google::protobuf::int32 ATQuote::bidsize() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.bidSize)
  return bidsize_;
}
inline void ATQuote::set_bidsize(::google::protobuf::int32 value) {
  set_has_bidsize();
  bidsize_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATQuote.bidSize)
}

// optional int32 askSize = 5;
inline bool ATQuote::has_asksize() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ATQuote::set_has_asksize() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ATQuote::clear_has_asksize() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ATQuote::clear_asksize() {
  asksize_ = 0;
  clear_has_asksize();
}
inline ::google::protobuf::int32 ATQuote::asksize() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.askSize)
  return asksize_;
}
inline void ATQuote::set_asksize(::google::protobuf::int32 value) {
  set_has_asksize();
  asksize_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATQuote.askSize)
}

// optional int32 quoteConditionId = 6;
inline bool ATQuote::has_quoteconditionid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ATQuote::set_has_quoteconditionid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ATQuote::clear_has_quoteconditionid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ATQuote::clear_quoteconditionid() {
  quoteconditionid_ = 0;
  clear_has_quoteconditionid();
}
inline ::google::protobuf::int32 ATQuote::quoteconditionid() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.quoteConditionId)
  return quoteconditionid_;
}
inline void ATQuote::set_quoteconditionid(::google::protobuf::int32 value) {
  set_has_quoteconditionid();
  quoteconditionid_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATQuote.quoteConditionId)
}

// optional .NodeActiveTickProto.ATServerTime serverTime = 7;
inline bool ATQuote::has_servertime() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ATQuote::set_has_servertime() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ATQuote::clear_has_servertime() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ATQuote::clear_servertime() {
  if (servertime_ != NULL) servertime_->::NodeActiveTickProto::ATServerTime::Clear();
  clear_has_servertime();
}
inline const ::NodeActiveTickProto::ATServerTime& ATQuote::servertime() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.serverTime)
  return servertime_ != NULL ? *servertime_ : *default_instance_->servertime_;
}
inline ::NodeActiveTickProto::ATServerTime* ATQuote::mutable_servertime() {
  set_has_servertime();
  if (servertime_ == NULL) servertime_ = new ::NodeActiveTickProto::ATServerTime;
  // @@protoc_insertion_point(field_mutable:NodeActiveTickProto.ATQuote.serverTime)
  return servertime_;
}
inline ::NodeActiveTickProto::ATServerTime* ATQuote::release_servertime() {
  clear_has_servertime();
  ::NodeActiveTickProto::ATServerTime* temp = servertime_;
  servertime_ = NULL;
  return temp;
}
inline void ATQuote::set_allocated_servertime(::NodeActiveTickProto::ATServerTime* servertime) {
  delete servertime_;
  servertime_ = servertime;
  if (servertime) {
    set_has_servertime();
  } else {
    clear_has_servertime();
  }
  // @@protoc_insertion_point(field_set_allocated:NodeActiveTickProto.ATQuote.serverTime)
}

// optional int32 bidExchangeId = 8;
inline bool ATQuote::has_bidexchangeid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ATQuote::set_has_bidexchangeid() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ATQuote::clear_has_bidexchangeid() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ATQuote::clear_bidexchangeid() {
  bidexchangeid_ = 0;
  clear_has_bidexchangeid();
}
inline ::google::protobuf::int32 ATQuote::bidexchangeid() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.bidExchangeId)
  return bidexchangeid_;
}
inline void ATQuote::set_bidexchangeid(::google::protobuf::int32 value) {
  set_has_bidexchangeid();
  bidexchangeid_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATQuote.bidExchangeId)
}

// optional int32 askExchangeId = 9;
inline bool ATQuote::has_askexchangeid() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ATQuote::set_has_askexchangeid() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ATQuote::clear_has_askexchangeid() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ATQuote::clear_askexchangeid() {
  askexchangeid_ = 0;
  clear_has_askexchangeid();
}
inline ::google::protobuf::int32 ATQuote::askexchangeid() const {
  // @@protoc_insertion_point(field_get:NodeActiveTickProto.ATQuote.askExchangeId)
  return askexchangeid_;
}
inline void ATQuote::set_askexchangeid(::google::protobuf::int32 value) {
  set_has_askexchangeid();
  askexchangeid_ = value;
  // @@protoc_insertion_point(field_set:NodeActiveTickProto.ATQuote.askExchangeId)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace NodeActiveTickProto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_2eproto__INCLUDED
